### ISSUE TITLE
Proposal - release this as v1.0.0 (chore)

### ISSUE THREAD

**Issue by scott-wyatt** [trailsjs/trails-controller#3]
I haven't seen any updates here in a while, are we ready to release this out of beta?

**Comment by scott-wyatt** [comment]
@trailsjs/maintainers any opinions on this? The road map says we should be looking at a 2.0 right now.

**Comment by jaumard** [comment]
Yes all trails-"api" should now be at least in 1.0.0

**Comment by scott-wyatt** [comment]
Cool, @jaumard do you have the ability to do this? I do not.

**Comment by jaumard** [comment]
I can try :)

**Comment by jaumard** [comment]
@scott-wyatt no I can't too don't have access. @tjwebb help :D

**Comment by jaumard** [comment]
@scott-wyatt all trails-.... are now in v1
